language: cpp
os:
  - osx

compiler:
  - clang

before_script:
  - pip install --user cpp-coveralls

script:
  - mkdir -p build
  - cd build
  - cmake -DCOVERAGE=ON ..
  - cmake --build . -j 4
  - ctest

after_success:
  - cpp-coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
