language: cpp
os: osx

sudo: required
dist: trusty

compiler:
  - clang

before_script:
  - brew update
  - brew install python3
  - pip install --user cpp-coveralls
  - export PATH=$HOME/.local/bin:$PATH

script:
  - mkdir -p build
  - cd build
  - cmake -DCOVERAGE=ON ..
  - cmake --build . -j 4
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --verbose
