language: cpp
os: osx

sudo: required
dist: trusty

compiler:
  - clang

before_script:
  - export PATH=$HOME/Library/Python/2.7/bin:$PATH
  - pip install --user cpp-coveralls

script:
  - mkdir -p build
  - cd build
  - cmake -DCOVERAGE=ON ..
  - cmake --build . -j 4
  - ctest

after_success:
  - coveralls --root .. -e third_party -e examples -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" --verbose